### PR TITLE
If a fieldmap has allowed record types, use them to constrain the SOQL sent to Salesforce

### LINKED ISSUE #383: SOQL queries don't use the Salesforce record types to filter results
**Describe the bug**
When a Salesforce object type has record types associated with it, we show them to users who are working with fieldmaps. All of the record types are displayed with checkboxes as "allowed record types" and one of them has a dropdown for "default record type." The default record type, if it exists, is what a record is saved as when it is pushed from WordPress.

We use this setting info in various places throughout the plugin, but we don't currently use it to filter the SOQL query that pulls updated records from Salesforce. This can cause queries to be much bigger than they need to be.

**To Reproduce**
1. Make a fieldmap that uses a Salesforce object type with record types (ex Opportunity) that pulls data from Salesforce. Check some of the allowed record types but not all of them
2. Log the SOQL query that it runs
3. Optionally log the records that it loops through

**Expected behavior**
I think the SOQL query should only pull records where the record type is one of the allowed record types. The pull query can ignore the default record type, I think.

**Screenshots**
The screen looks like this. 
image

**Additional context**
I'm a little worried about why I overlooked this for so long. I'd like to look through the history of the file a little and just make sure there wasn't some weird intentionality in this.

### PR DESCRIPTION
**Pull request by jonathanstegall**
## What does this Pull Request do?

If a fieldmap has allowed record types, use them to constrain the SOQL query that is used to pull updated records from Salesforce. This should fix #383.

## How do I test this Pull Request?

- I think make fieldmaps that do and that do not use "allowed record types" and make sure it works in both cases.

### CODE REVIEW

File: classes/salesforce_pull.php [hunk 1]
```diff
@@ -797,6 +797,11 @@ function change_pull_query( $soql, $type, $salesforce_mapping, $mapped_fields )
 			$soql->conditions = array_map( 'unserialize', array_unique( array_map( 'serialize', $soql->conditions ) ) );
 		}
 
+		// if there are record types on this fieldmap, use them as a conditional
+		if ( ! empty( $mapped_record_types ) ) {
+			$soql->add_condition( 'RecordTypeId', array_values( $mapped_record_types ), 'IN' );
+		}
+
 		// serialize the currently running SOQL query and store it for this type
```
Comment (minncodebot) [inline classes/salesforce_pull.php:805]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 2]
```diff
@@ -797,6 +797,11 @@ function change_pull_query( $soql, $type, $salesforce_mapping, $mapped_fields )
 			$soql->conditions = array_map( 'unserialize', array_unique( array_map( 'serialize', $soql->conditions ) ) );
 		}
 
+		// if there are record types on this fieldmap, use them as a conditional
```
Comment (minncodebot) [inline classes/salesforce_pull.php:800]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
**phpcs** scanning turned up:

:no_entry_sign: 2 errors 

***

**hashes-api**-scanning skipped

File: classes/salesforce_pull.php [hunk 3]
```diff
@@ -2290,7 +2295,7 @@ private function create_object_map( $salesforce_object, $wordpress_id, $field_ma
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2295]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:2295]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 4]
```diff
@@ -773,10 +773,10 @@ private function get_pull_query( $type, $salesforce_mapping = array() ) {
...
 
 		// add a filter here to modify the query
-		// Hook to allow other plugins to modify the SOQL query before it is sent to Salesforce
+		// Hook to allow other plugins to modify the SOQL query before it is sent to Salesforce.
 		$soql = apply_filters( $this->option_prefix . 'pull_query_modify', $soql, $type, $salesforce_mapping, $mapped_fields );
 
-		// quick example to change the order to descending
+		// quick example to change the order to descending.
 		/*
 		add_filter( 'object_sync_for_salesforce_pull_query_modify', 'change_pull_query', 10, 4 );
```
Comment (minncodebot) [inline classes/salesforce_pull.php:781]: :no_entry_sign: **Error**: Block comments must start with a capital letter (*Squiz.Commenting.BlockComment.NoCapital*).

File: classes/salesforce_pull.php [hunk 5]
```diff
@@ -773,10 +773,10 @@ private function get_pull_query( $type, $salesforce_mapping = array() ) {
 		$soql->offset = $this->get_pull_offset( $type, $soql, $reset_offset );
 
 		// add a filter here to modify the query
-		// Hook to allow other plugins to modify the SOQL query before it is sent to Salesforce
+		// Hook to allow other plugins to modify the SOQL query before it is sent to Salesforce.
 		$soql = apply_filters( $this->option_prefix . 'pull_query_modify', $soql, $type, $salesforce_mapping, $mapped_fields );
 
-		// quick example to change the order to descending
+		// quick example to change the order to descending.
 		/*
```
Comment (minncodebot) [inline classes/salesforce_pull.php:780]: :no_entry_sign: **Error**: Empty line required before block comment (*Squiz.Commenting.BlockComment.NoEmptyLineBefore*).

Comment (minncodebot) [inline classes/salesforce_pull.php:780]: :warning: **Warning**: This comment is 57% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 6]
```diff
@@ -751,7 +751,7 @@ private function get_pull_query( $type, $salesforce_mapping = array() ) {
 		// Get the value for the pull trigger field. Often this will LastModifiedDate. It needs to change when the query gets regenerated after the max offset has been reached.
 		$pull_trigger_field_value = $this->get_pull_date_value( $type, $soql );
 
-		// we check to see if the stored date is the same as the new one. if it is not, we will want to reset the offset
+		// we check to see if the stored date is the same as the new one. if it is not, we will want to reset the offset.
 		$reset_offset = false;
 		$has_date     = false;
 		$key          = array_search( $salesforce_mapping['pull_trigger_field'], array_column( $soql->conditions, 'field' ) );
```
Comment (minncodebot) [inline classes/salesforce_pull.php:757]: :warning: **Warning**: Not using strict comparison for array_search; supply true for third argument (*WordPress.PHP.StrictInArray.MissingTrueStrict*).

File: classes/salesforce_pull.php [hunk 7]
```diff
@@ -732,12 +732,12 @@ private function get_pull_query( $type, $salesforce_mapping = array() ) {
 				)
 			);
 
-			// these are bit operators, so we leave out the strict
+			// these are bit operators, so we leave out the strict.
 			if ( in_array( $this->mappings->sync_sf_create, $salesforce_mapping['sync_triggers'] ) ) {
```
Comment (minncodebot) [inline classes/salesforce_pull.php:736]: :warning: **Warning**: Not using strict comparison for in_array; supply true for third argument (*WordPress.PHP.StrictInArray.MissingTrueStrict*).

File: classes/salesforce_pull.php [hunk 8]
```diff
@@ -576,7 +576,7 @@ private function get_updated_records() {
 	*
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:577]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:577]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 9]
```diff
@@ -576,7 +576,7 @@ private function get_updated_records() {
 	*
```
Comment (minncodebot) [inline classes/salesforce_pull.php:576]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
**phpcs** scanning turned up:

:no_entry_sign: 24 errors 

:warning: 4 warnings 

***

**hashes-api**-scanning skipped


Posting will continue in further review(s)

File: classes/salesforce_pull.php [hunk 10]
```diff
@@ -528,7 +528,7 @@ private function get_updated_records() {
 
 				$logging->setup( $result );
 			} elseif ( isset( $response['errorCode'] ) ) {
-				// create log entry for failed pull
+				// create log entry for failed pull.
 				$status = 'error';
 				$title  = sprintf(
 					// translators: placeholders are: 1) the log status, 2) the server error code, and 3) the name of the Salesforce object
```
Comment (minncodebot) [inline classes/salesforce_pull.php:534]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 11]
```diff
@@ -482,13 +482,13 @@ private function get_updated_records() {
...
 					$this->clear_current_type_query( $type );
 				}
-				// try to check for specific error codes from Salesforce
+				// try to check for specific error codes from Salesforce.
 			} elseif ( isset( $response['errorCode'] ) && 'INVALID_FIELD' === $response['errorCode'] ) {
-				// set up log entry
+				// set up log entry.
 				$status    = 'error';
 				$log_title = sprintf(
 					// translators: placeholders are: 1) the log status, 2) the server error code, and 3) the name of the Salesforce object
```
Comment (minncodebot) [inline classes/salesforce_pull.php:494]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 12]
```diff
@@ -428,13 +428,13 @@ private function get_updated_records() {
 							),
 							$this->schedule_name
 						);
-						// update the current state so we don't end up on the same record again if the loop fails
+						// update the current state so we don't end up on the same record again if the loop fails.
 						update_option( $this->option_prefix . 'last_pull_id', $result['Id'] );
 						if ( 1 === (int) $this->debug ) {
 							// create log entry for successful pull
```
Comment (minncodebot) [inline classes/salesforce_pull.php:434]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 13]
```diff
@@ -330,33 +330,33 @@ private function get_updated_records() {
...
 					if ( isset( $result['CreatedDate'] ) && $result['CreatedDate'] > $last_sync ) {
 						$sf_sync_trigger = $this->mappings->sync_sf_create;
 					} else {
 						$sf_sync_trigger = $this->mappings->sync_sf_update;
 					}
 
 					// Only queue when the record's trigger is configured for the mapping
-					// these are bit operators, so we leave out the strict
+					// these are bit operators, so we leave out the strict.
 					if ( isset( $map_sync_triggers ) && isset( $sf_sync_trigger ) && in_array( $sf_sync_trigger, $map_sync_triggers ) ) { // wp or sf crud event
```
Comment (minncodebot) [inline classes/salesforce_pull.php:342]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

Comment (minncodebot) [inline classes/salesforce_pull.php:342]: :warning: **Warning**: Not using strict comparison for in_array; supply true for third argument (*WordPress.PHP.StrictInArray.MissingTrueStrict*).

File: classes/salesforce_pull.php [hunk 14]
```diff
@@ -134,14 +134,14 @@ public function add_actions() {
 	*/
 	public function salesforce_pull_webhook( WP_REST_Request $request ) {
```
Comment (minncodebot) [inline classes/salesforce_pull.php:135]: :no_entry_sign: **Error**: Expected type hint &quot;object&quot;; found &quot;WP_REST_Request&quot; for $request (*Squiz.Commenting.FunctionComment.IncorrectTypeHint*).

File: classes/salesforce_pull.php [hunk 15]
```diff
@@ -134,14 +134,14 @@ public function add_actions() {
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:134]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:134]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 16]
```diff
@@ -111,10 +111,10 @@ private function batch_soql_queries( $batch_soql_queries ) {
...
```
Comment (minncodebot) [inline classes/salesforce_pull.php:111]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:111]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
Previous scan continued.

File: classes/salesforce_pull.php [hunk 17]
```diff
@@ -95,7 +95,7 @@ public function __construct( $wpdb, $version, $login_credentials, $slug, $wordpr
 	*
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:96]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:96]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 18]
```diff
@@ -95,7 +95,7 @@ public function __construct( $wpdb, $version, $login_credentials, $slug, $wordpr
 	*
```
Comment (minncodebot) [inline classes/salesforce_pull.php:95]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 19]
```diff
@@ -75,7 +75,7 @@ public function __construct( $wpdb, $version, $login_credentials, $slug, $wordpr
 		// Maximum offset size for a SOQL query to Salesforce
 		// See: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_offset.htm
 		// "The maximum offset is 2,000 rows. Requesting an offset greater than 2,000 results in a NUMBER_OUTSIDE_VALID_RANGE error."
```
Comment (minncodebot) [inline classes/salesforce_pull.php:77]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 20]
```diff
@@ -36,7 +36,7 @@ class Object_Sync_Sf_Salesforce_Pull {
 	/**
 	* @var string
 	*/
-	public $schedule_name; // allow for naming the queue in case there are multiple queues
+	public $schedule_name; // allow for naming the queue in case there are multiple queues.
 
 	/**
 	* Constructor which sets up pull schedule
```
Comment (minncodebot) [inline classes/salesforce_pull.php:42]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 21]
```diff
@@ -36,7 +36,7 @@ class Object_Sync_Sf_Salesforce_Pull {
 	/**
 	* @var string
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:38]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 22]
```diff
@@ -36,7 +36,7 @@ class Object_Sync_Sf_Salesforce_Pull {
 	/**
 	* @var string
```
Comment (minncodebot) [inline classes/salesforce_pull.php:37]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 23]
```diff
@@ -36,7 +36,7 @@ class Object_Sync_Sf_Salesforce_Pull {
 	/**
```
Comment (minncodebot) [inline classes/salesforce_pull.php:36]: :no_entry_sign: **Error**: Missing short description in doc comment (*Generic.Commenting.DocComment.MissingShort*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
Previous scan continued.

**Comment by jonathanstegall** [comment]
This isn't right just yet. From logging the SOQL query:

```php
[08-Mar-2021 17:05:44 UTC] query is SELECT Id, LastModifiedDate, CreatedDate FROM Opportunity WHERE LastModifiedDate > 2021-02-12T04:21:29Z AND RecordTypeId IN ('0120G0000016KlXQAU','012F00000013GkqIAE') ORDER BY LastModifiedDate ASC LIMIT 25
[08-Mar-2021 17:06:57 UTC] query is SELECT Id, LastModifiedDate, CreatedDate FROM Opportunity WHERE LastModifiedDate > 2021-02-12T04:21:46Z AND RecordTypeId IN ('0120G0000016KlXQAU','012F00000013GkqIAE') AND RecordTypeId IN ('0120G0000016KlXQAU','012F00000013GkqIAE') ORDER BY LastModifiedDate ASC LIMIT 25 OFFSET 50
```

So it works correctly the first time, but then when it increments the query on subsequent runs it just keeps doing it. That's not a fix.

File: classes/salesforce_pull.php [hunk 24]
```diff
@@ -2302,7 +2307,7 @@ private function is_pull_allowed( $object_type, $object, $sf_sync_trigger, $sale
 		}
 
 		// Hook to allow other plugins to prevent a pull per-mapping.
-		// Putting the pull_allowed hook here will keep the queue from storing data when it is not supposed to store it
+		// Putting the pull_allowed hook here will keep the queue from storing data when it is not supposed to store it.
 		$pull_allowed = apply_filters( $this->option_prefix . 'pull_object_allowed', $pull_allowed, $object_type, $object, $sf_sync_trigger, $salesforce_mapping );
 
 		// example to keep from pulling the Contact with id of abcdef
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2313]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 25]
```diff
@@ -2253,12 +2258,12 @@ private function increment_current_type_datetime( $type, $next_query_modified_da
 	*
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2259]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:2259]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 26]
```diff
@@ -2253,12 +2258,12 @@ private function increment_current_type_datetime( $type, $next_query_modified_da
 	*
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2258]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 27]
```diff
@@ -2229,7 +2234,7 @@ public function clear_current_type_query( $type ) {
...
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2235]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:2235]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 28]
```diff
@@ -2229,7 +2234,7 @@ public function clear_current_type_query( $type ) {
 	*
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2234]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 29]
```diff
@@ -2211,11 +2216,11 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
...
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2217]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:2217]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 30]
```diff
@@ -2211,11 +2216,11 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
 	*
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2216]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
**phpcs** scanning turned up:

:no_entry_sign: 15 errors 

:warning: 18 warnings 

***

**hashes-api**-scanning skipped


Posting will continue in further review(s)

File: classes/salesforce_pull.php [hunk 31]
```diff
@@ -2193,9 +2198,9 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
 					$logging->setup( $notice );
 				} // End if() on count
 				// delete the map row from WordPress after the WordPress row has been deleted
-				// we delete the map row even if the WordPress delete failed, because the Salesforce object is gone
+				// we delete the map row even if the WordPress delete failed, because the Salesforce object is gone.
 				$this->mappings->delete_object_map( $mapping_object['id'] );
-				// there is no map row if we end this if statement
+				// there is no map row if we end this if statement.
 			} // End if().
 		} // End if().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2205]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 32]
```diff
@@ -2193,9 +2198,9 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
 					$logging->setup( $notice );
 				} // End if() on count
 				// delete the map row from WordPress after the WordPress row has been deleted
-				// we delete the map row even if the WordPress delete failed, because the Salesforce object is gone
+				// we delete the map row even if the WordPress delete failed, because the Salesforce object is gone.
 				$this->mappings->delete_object_map( $mapping_object['id'] );
-				// there is no map row if we end this if statement
+				// there is no map row if we end this if statement.
 			} // End if().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2204]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 33]
```diff
@@ -2144,13 +2149,13 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
 
 						$results[] = $result;
 
-						// hook for pull success
+						// hook for pull success.
 						do_action( $this->option_prefix . 'pull_success', $op, $result, $synced_object );
 					} // End if() successful
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2154]: :warning: **Warning**: This comment is 43% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 34]
```diff
@@ -2106,13 +2111,13 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
 							$exception = new $my_class( $e->getMessage(), $e->getCode(), $exception );
 						}
 
-						// hook for pull fail
+						// hook for pull fail.
 						do_action( $this->option_prefix . 'pull_fail', $op, $result, $synced_object );
 
 					} // End try().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2117]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 35]
```diff
@@ -2045,17 +2050,17 @@ private function delete_called_from_salesforce( $sf_sync_trigger, $synced_object
...
 
-		// methods to run the wp delete operations
+		// methods to run the wp delete operations.
 		$results = array();
 		$op      = '';
 
-		// deleting mapped objects
-		if ( $sf_sync_trigger == $this->mappings->sync_sf_delete ) { // trigger is a bit operator
+		// deleting mapped objects.
+		if ( $sf_sync_trigger == $this->mappings->sync_sf_delete ) { // trigger is a bit operator.
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2058]: :warning: **Warning**: Found: ==. Use strict comparisons (=== or !==) (*WordPress.PHP.StrictComparisons.LooseComparison*).

File: classes/salesforce_pull.php [hunk 36]
```diff
@@ -2004,19 +2009,19 @@ private function update_called_from_salesforce( $sf_sync_trigger, $synced_object
 				$exception = new $my_class( $e->getMessage(), $e->getCode(), $exception );
 			}
 
-			// hook for pull fail
+			// hook for pull fail.
 			do_action( $this->option_prefix . 'pull_fail', $op, $result, $synced_object );
 
 		} // End try().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:2015]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 37]
```diff
@@ -1870,7 +1875,7 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 
 			$results[] = $result;
 
-			// hook for pull fail
+			// hook for pull fail.
 			do_action( $this->option_prefix . 'pull_fail', $op, $result, $synced_object );
 
 		} // End if().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1881]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 38]
```diff
@@ -1850,12 +1855,12 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
...
 
 			$body = sprintf(
-				// translators: placeholders are: 1) the name of the WordPress object type, 2) the WordPress id field name, 3) the WordPress id field value, 4) the array of errors
+				// translators: placeholders are: 1) the name of the WordPress object type, 2) the WordPress id field name, 3) the WordPress id field value, 4) the array of errors.
 				'<p>' . esc_html__( 'Object: %1$s with %2$s of %3$s', 'object-sync-for-salesforce' ) . '</p><p>' . esc_html__( 'Message: ', 'object-sync-for-salesforce' ) . '%4$s' . '</p>',
 				esc_attr( $salesforce_mapping['wordpress_object'] ),
 				esc_attr( $wordpress_id_field_name ),
 				esc_attr( $wordpress_id ),
-				print_r( $result['errors'], true ) // if we get this error, we need to know whatever we have
+				print_r( $result['errors'], true ) // if we get this error, we need to know whatever we have.
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1863]: :warning: **Warning**: print_r() found. Debug code should not normally be used in production (*WordPress.PHP.DevelopmentFunctions.error_log_print_r*).

File: classes/salesforce_pull.php [hunk 39]
```diff
@@ -1850,12 +1855,12 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 			);
 
 			$body = sprintf(
-				// translators: placeholders are: 1) the name of the WordPress object type, 2) the WordPress id field name, 3) the WordPress id field value, 4) the array of errors
+				// translators: placeholders are: 1) the name of the WordPress object type, 2) the WordPress id field name, 3) the WordPress id field value, 4) the array of errors.
 				'<p>' . esc_html__( 'Object: %1$s with %2$s of %3$s', 'object-sync-for-salesforce' ) . '</p><p>' . esc_html__( 'Message: ', 'object-sync-for-salesforce' ) . '%4$s' . '</p>',
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1859]: :no_entry_sign: **Error**: String concat is not required here; use a single string instead (*Generic.Strings.UnnecessaryStringConcat.Found*).

File: classes/salesforce_pull.php [hunk 40]
```diff
@@ -1836,12 +1841,12 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 			}
 
 			if ( is_object( $wordpress_id ) ) {
-				// print this array because if this happens, something weird has happened and we want to log whatever we have
+				// print this array because if this happens, something weird has happened and we want to log whatever we have.
 				$wordpress_id = print_r( $wordpress_id, true );
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1845]: :warning: **Warning**: print_r() found. Debug code should not normally be used in production (*WordPress.PHP.DevelopmentFunctions.error_log_print_r*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
Previous scan continued.

File: classes/salesforce_pull.php [hunk 41]
```diff
@@ -1767,12 +1772,12 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 				$exception = new $my_class( $e->getMessage(), $e->getCode(), $exception );
 			}
 
-			// hook for pull fail
+			// hook for pull fail.
 			do_action( $this->option_prefix . 'pull_fail', $op, $result, $synced_object );
 
 		} // End try().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1778]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 42]
```diff
@@ -1711,10 +1716,10 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 				$result = $this->wordpress->object_create( $salesforce_mapping['wordpress_object'], $params );
 			} // End if().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1717]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 43]
```diff
@@ -1625,15 +1630,15 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 					} // End if().
 				} // End if().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1631]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 44]
```diff
@@ -1625,15 +1630,15 @@ private function create_called_from_salesforce( $sf_sync_trigger, $synced_object
 					} // End if().
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1630]: :warning: **Warning**: This comment is 50% valid code; is this commented out code? (*Squiz.PHP.CommentedOutCode.Found*).

File: classes/salesforce_pull.php [hunk 45]
```diff
@@ -1461,12 +1466,12 @@ public function salesforce_pull_process_records( $object_type, $object, $sf_sync
 	*/
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1466]: :no_entry_sign: **Error**: Additional blank lines found at end of doc comment (*Generic.Commenting.DocComment.SpacingAfter*).

Comment (minncodebot) [inline classes/salesforce_pull.php:1466]: :no_entry_sign: **Error**: Expected 5 space(s) before asterisk; 4 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

File: classes/salesforce_pull.php [hunk 46]
```diff
@@ -1386,15 +1391,15 @@ public function salesforce_pull_process_records( $object_type, $object, $sf_sync
 
 				// if there is an external key field in Salesforce - ie a Mailchimp user id - on the fieldmap object, this should not affect how WordPress handles it is not included in the pull parameters.
 
-				// if we don't get any params, there are no fields that should be sent to WordPress
+				// if we don't get any params, there are no fields that should be sent to WordPress.
 				if ( empty( $params ) ) {
 					return;
 				}
 			} elseif ( $sf_sync_trigger == $this->mappings->sync_sf_delete ) {
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1398]: :warning: **Warning**: Found: ==. Use strict comparisons (=== or !==) (*WordPress.PHP.StrictComparisons.LooseComparison*).

File: classes/salesforce_pull.php [hunk 47]
```diff
@@ -1357,20 +1362,20 @@ public function salesforce_pull_process_records( $object_type, $object, $sf_sync
 			$structure               = $this->wordpress->get_wordpress_table_structure( $salesforce_mapping['wordpress_object'] );
 			$wordpress_id_field_name = $structure['id_field'];
 
-			// don't do parameters if we are deleting
+			// don't do parameters if we are deleting.
 			if ( ( true === $is_new && $sf_sync_trigger == $this->mappings->sync_sf_create ) || $sf_sync_trigger == $this->mappings->sync_sf_update ) { // trigger is a bit operator
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1366]: :warning: **Warning**: Found: ==. Use strict comparisons (=== or !==) (*WordPress.PHP.StrictComparisons.LooseComparison*).

File: classes/salesforce_pull.php [hunk 48]
```diff
@@ -1261,15 +1266,15 @@ public function salesforce_pull_process_records( $object_type, $object, $sf_sync
...
 				$title = sprintf(
-					// translators: placeholders are: 1) the log status
+					// translators: placeholders are: 1) the log status.
 					esc_html__( '%1$s: Salesforce Pull: unable to process queue item because it has no Salesforce Id.', 'object-sync-for-salesforce' ),
 					ucfirst( esc_attr( $status ) )
 				);
 				$result = array(
 					'title'   => $title,
-					'message' => print_r( $object, true ), // log whatever we have in the event of this error, so print the array
+					'message' => print_r( $object, true ), // log whatever we have in the event of this error, so print the array.
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1275]: :warning: **Warning**: print_r() found. Debug code should not normally be used in production (*WordPress.PHP.DevelopmentFunctions.error_log_print_r*).

File: classes/salesforce_pull.php [hunk 49]
```diff
@@ -1182,7 +1187,7 @@ public function salesforce_pull_process_records( $object_type, $object, $sf_sync
 			$salesforce_id = $object;
 			// Load the Salesforce object data to save in WordPress. We need to make sure that this data does not get cached, which is consistent with other pull behavior as well as in other methods in this class.
 			// We should only do this if we're not trying to delete data in WordPress - otherwise, we'll get a 404 from Salesforce and the delete will fail.
-			if ( $sf_sync_trigger != $this->mappings->sync_sf_delete ) { // trigger is a bit operator
+			if ( $sf_sync_trigger != $this->mappings->sync_sf_delete ) { // trigger is a bit operator.
```
Comment (minncodebot) [inline classes/salesforce_pull.php:1190]: :warning: **Warning**: Found: !=. Use strict comparisons (=== or !==) (*WordPress.PHP.StrictComparisons.LooseComparison*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
Previous scan continued.

File: classes/salesforce_pull.php [hunk 50]
```diff
@@ -590,22 +590,22 @@ private function get_next_record_batch( $last_sync, $salesforce_mapping, $map_sy
...
-						// Only queue when the record's trigger is configured for the mapping
-					// these are bit operators, so we leave out the strict
+					// Only queue when the record's trigger is configured for the mapping
+					// these are bit operators, so we leave out the strict.
 					if ( isset( $map_sync_triggers ) && isset( $sf_sync_trigger ) && in_array( $sf_sync_trigger, $map_sync_triggers ) ) { // wp or sf crud event
 						$data = array(
 							'object_type'     => $type,
 							'object'          => $result,
 							'mapping'         => $salesforce_mapping,
 							'sf_sync_trigger' => $sf_sync_trigger, // use the appropriate trigger based on when this was created
```
Comment (minncodebot) [inline classes/salesforce_pull.php:606]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

File: classes/salesforce_pull.php [hunk 51]
```diff
@@ -590,22 +590,22 @@ private function get_next_record_batch( $last_sync, $salesforce_mapping, $map_sy
...
 					if ( isset( $result['CreatedDate'] ) && $result['CreatedDate'] > $last_sync ) {
 						$sf_sync_trigger = $this->mappings->sync_sf_create;
 					} else {
 						$sf_sync_trigger = $this->mappings->sync_sf_update;
 					}
-						// Only queue when the record's trigger is configured for the mapping
-					// these are bit operators, so we leave out the strict
+					// Only queue when the record's trigger is configured for the mapping
+					// these are bit operators, so we leave out the strict.
 					if ( isset( $map_sync_triggers ) && isset( $sf_sync_trigger ) && in_array( $sf_sync_trigger, $map_sync_triggers ) ) { // wp or sf crud event
```
Comment (minncodebot) [inline classes/salesforce_pull.php:601]: :no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

Comment (minncodebot) [inline classes/salesforce_pull.php:601]: :warning: **Warning**: Not using strict comparison for in_array; supply true for third argument (*WordPress.PHP.StrictInArray.MissingTrueStrict*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
Previous scan continued.
