### PR TITLE
As part of the work to support multiple fieldmaps on the same Salesforce object type, object maps need to be loaded with information about the fieldmap.

### LINKED ISSUE #437: When loading multiple object maps for the same Salesforce object, the fieldmap needs to be specified
**Describe the bug**
In #420, we have the ability for multiple fieldmaps to work with the same Salesforce object. However, the `load_all_by_salesforce` method on `Object_Sync_Sf_Mapping` is not fieldmap-specific, so it loads object maps that are not part of the desired fieldmap.

This isn't exactly a bug since it's part of a new feature that hasn't been released yet.

**To Reproduce**
1. create two fieldmaps that work with the same Salesforce object
2. modify data on a record in Salesforce and watch the logs

### PR DESCRIPTION
**Pull request by jonathanstegall**
## What does this Pull Request do?

This fixes #437 by adding a new method, `load_object_maps_by_salesforce`, that takes the fieldmap as a parameter so we can specify the WordPress object type when loading object maps that are tied to a Salesforce ID.

This also deprecates `load_all_by_salesforce`.

## How do I test this Pull Request?

Same steps as #420.

### CODE REVIEW

File: classes/class-object-sync-sf-mapping.php [hunk 1]
```diff
@@ -899,20 +899,37 @@ public function load_all_by_wordpress( $object_type, $object_id, $reset = false
 	 * Returns Salesforce object mappings for a given Salesforce object.
 	 *
 	 * @param string $salesforce_id Type of object to load.
+	 * @param array $fieldmap the fieldmap this object map works with.
```
Comment (minncodebot) [inline classes/class-object-sync-sf-mapping.php:902]: :no_entry_sign: **Error**: Expected 2 spaces after parameter type; 1 found (*Squiz.Commenting.FunctionComment.SpacingAfterParamType*).

**Review by minncodebot — CHANGES_REQUESTED** [review]
**phpcs** scanning turned up:

:no_entry_sign: 1 error 

***

**hashes-api**-scanning skipped
