### PR TITLE
Duplicate mapping of fields was prevented when it shouldn't be. Thanks to @timnolte for the report.

### LINKED ISSUE #415: New Option to Disable Already Used Mapping Fields is Stuck On
**Describe the bug**
The new plugin setting that disables the reuse of already mapping WordPress and Salesforce fields seems to be stuck always on. Setting this flag on the plugin options screen has no affect and already mapped fields are always disabled. Note that we also have the

**To Reproduce**
1. Ensure the new "Prevent Duplicate Field Mapping?" option is unchecked.
2. Add/edit a Field Mapping.
3. Map some WordPress fields to Salesforce.
4. Save & reload the Field Mapping.
5. Fields already mapped are disabled and cannot be selected.

**Expected behavior**
If the option "Prevent Duplicate Field Mapping?" is not enabled, or disabled again after having been enabled editing a field mapping should allow WordPress and Salesforce fields to be mapped again.

**Screenshots**
https://imgur.com/a/Kzlp4ol
https://imgur.com/a/BihAV4Q

**Environment (please complete the following information):**
 - WordPress Version: 5.7.2
 - Object Sync Plugin: 2.0.1
 - Other relevant plugins:
  - ACF 5.9.5
  - Gravity Forms 2.4.23
  - The Events Calendar 5.4.0.2
 - PHP Version: 7.4

### PR DESCRIPTION
**Pull request by jonathanstegall**
## What does this Pull Request do?

This fixes #415 by only disabling already mapped fields when the setting is enabled, as it should be.

### bug fix
- Ensure the new "Prevent Duplicate Field Mapping?" option is unchecked.
- Add/edit a Field Mapping.
- Map some WordPress fields to Salesforce.
- Save & reload the Field Mapping.
- Fields already mapped should be selectable.

### that the option still works
- Ensure the new "Prevent Duplicate Field Mapping?" option is checked.
- Add/edit a Field Mapping.
- Map some WordPress fields to Salesforce.
- Save & reload the Field Mapping.
- Fields already mapped should not be selectable.

### CODE REVIEW

File: templates/admin/fieldmaps-add-edit-clone.php [hunk 1]
```diff
@@ -383,21 +383,25 @@
...
-									array_walk(
-										$fieldmap_fields,
-										function( $v, $k ) use ( &$key, $needle ) {
-											if ( in_array( $needle, $v['wordpress_field'], true ) ) {
-												$key = $k;
+									$disabled              = '';
+									$disable_mapped_fields = get_option( $this->option_prefix . 'disable_mapped_fields', false );
+									$disable_mapped_fields = filter_var( $disable_mapped_fields, FILTER_VALIDATE_BOOLEAN );
+									if ( true === $disable_mapped_fields ) {
+										$key      = null;
```
Comment (minncodebot) [inline templates/admin/fieldmaps-add-edit-clone.php:390]: :warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 4 spaces but found 6 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

File: templates/admin/fieldmaps-add-edit-clone.php [hunk 2]
```diff
@@ -383,21 +383,25 @@
...
+										$needle   = $wordpress_field['key']; // the current WP field.
```
Comment (minncodebot) [inline templates/admin/fieldmaps-add-edit-clone.php:391]: :warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 1 space but found 3 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

File: templates/admin/fieldmaps-add-edit-clone.php [hunk 3]
```diff
@@ -423,21 +427,25 @@ function( $v, $k ) use ( &$key, $needle ) {
...
-									array_walk(
-										$fieldmap_fields,
-										function( $v, $k ) use ( &$key, $needle ) {
-											if ( in_array( $needle, $v['salesforce_field'], true ) ) {
-												$key = $k;
+									$disabled              = '';
+									$disable_mapped_fields = get_option( $this->option_prefix . 'disable_mapped_fields', false );
+									$disable_mapped_fields = filter_var( $disable_mapped_fields, FILTER_VALIDATE_BOOLEAN );
+									if ( true === $disable_mapped_fields ) {
+										$key      = null;
```
Comment (minncodebot) [inline templates/admin/fieldmaps-add-edit-clone.php:434]: :warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 4 spaces but found 6 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

File: templates/admin/fieldmaps-add-edit-clone.php [hunk 4]
```diff
@@ -423,21 +427,25 @@ function( $v, $k ) use ( &$key, $needle ) {
...
+										$needle   = $salesforce_field['name']; // the current Salesforce field.
```
Comment (minncodebot) [inline templates/admin/fieldmaps-add-edit-clone.php:435]: :warning: **Warning**: Equals sign not aligned with surrounding assignments; expected 1 space but found 3 spaces (*Generic.Formatting.MultipleStatementAlignment.NotSameWarning*).

**Review by minncodebot — COMMENTED** [review]
**phpcs** scanning turned up:

:warning: 4 warnings 

***

**hashes-api**-scanning skipped

**Comment by timnolte** [comment]
@jonathanstegall tested locally and things are working as expected.
